# -----------------------
# ----- Output Path -----
# -----------------------
output_path: /network/tmp1/schmidtv/yb_runs/test_v1
# -------------------
# -----  Tasks  -----
# -------------------
tasks: [A, D, H, T, W]
# ----------------
# ----- Data -----
# ----------------
data:
  files: # if one is not none it will override the dirs location
    base: /Users/victor/Documents/ccai/github/omnigan/example_data
    train:
      rf: train_rf.json
      rn: train_rn.json
      sf: train_sf.json
      sn: train_sn.json
    val:
      rf: val_rf.json
      rn: val_rn.json
      sf: val_sf.json
      sn: val_sn.json
  loaders:
    batch_size: 2
    shuffle: false
    num_workers: 8
  transforms:
    - name: hflip
      ignore: false
      p: 0.5
    - name: resize
      ignore: false
      new_size: 256
    - name: crop
      ignore: false
      height: 224
      width: 224
# ---------------------
# ----- Generator -----
# ---------------------
gen:
  opt:
    optimizer: ExtraAdam # one in [Adam, ExtraAdam] default: Adam
    lr_policy: false
    epoch_count: null # for linear decay
    niter: null # for linear or cosine decay
    niter_decay: null # for linear decay
    lr: 0.0005
    beta1: 0.9
  default:
    input_nc: 3
    output_nc: 3
    ngf: 64
    norm_layer: batch
    dropout: 0.2
    n_blocks: 6
    padding_type: reflect
    init_type: kaiming
    init_gain: 0.2
    lambda_rec: 1
    lambda_idt: 1
  A:
    lambda_idt: 5
# Set gen.A.init_gain to overwrite this parameter for A only
# -------------------------
# ----- Discriminator -----
# -------------------------
dis:
  opt:
    optimizer: ExtraAdam
    lr_policy: false
    epoch_count: null # for linear decay
    niter: null # for linear or cosine decay
    niter_decay: null # for linear decay
    lr: 0.0005
    beta1: 0.5
  default:
    input_nc: 3
    ndf: 64
    n_layers: 3
    norm: instance
    init_type: kaiming
    init_gain: 0.2
    use_sigmoid: false
# -------------------------------
# -----  Domain Classifier  -----
# -------------------------------
classifier:
  todo: true
# ------------------------
# ----- Train Params -----
# ------------------------
train:
  epochs: 1000
# -----------------------------
# ----- Validation Params -----
# -----------------------------
val:
  max_log_images: 15
  every_n_steps: 1000
  store_images: false
  infer_rec: true
  infer_idt: true # order: real, translated, rec, idt
