output_path: /network/tmp1/schmidtv/yb_runs/test_v1
# -------------------
# -----  Tasks  -----
# -------------------
tasks: [a, d, h, s, t, w]

# ----------------
# ----- Data -----
# ----------------
data:
  files: # if one is not none it will override the dirs location
    base: /path/to/data
    train:
      rf: train_rf.json
      rn: train_rn.json
      sf: train_sf.json
      sn: train_sn.json
    val:
      rf: val_rf.json
      rn: val_rn.json
      sf: val_sf.json
      sn: val_sn.json
  loaders:
    batch_size: 2
    shuffle: false
    num_workers: 8
  transforms:
    - name: hflip
      ignore: false
      p: 0.5
    - name: resize
      ignore: false
      new_size: 256
    - name: crop
      ignore: false
      height: 224
      width: 224
    - name: resize # ? this or change generator's output? Or resize larger then crop to 256?
      ignore: false
      new_size: 256

# ---------------------
# ----- Generator -----
# ---------------------
gen:
  opt:
    optimizer: ExtraAdam # one in [Adam, ExtraAdam] default: Adam
    beta1: 0.9
    lr: 0.0005
    lr_policy: step # constant or step ; if step, specify step_size and gamma
    lr_step_size: 30 # for linear decay : period of learning rate decay (epochs)
    lr_gamma: 0.5 # Multiplicative factor of learning rate decay
  default: # default parameters for the generator (encoder and decoders)
    activ: lrelu # activation function [relu/lrelu/prelu/selu/tanh]
    init_gain: 0.2
    init_type: kaiming
    n_res: 4 # number of residual blocks before upsampling
    n_upsample: 2 # upsampling in spade decoder ; should match encoder.n_downsample
    pad_type: reflect # padding type [zero/reflect]
    res_dim: 256 # Resblock number of channels (=latent space's)
    res_norm: "instance" # normalization to apply
  a: # specific params for the adaptation decoder
    output_dim: 3
  d: # specific params for the depth estimation decoder
    output_dim: 1
  h: # specific params for the height estimation decoder
    output_dim: 1
  s: # specific params for the semantic segmentation decoder
    num_classes: 19
    output_dim: 19
  t: # specific params for the translation SPADE decoder
    output_dim: 3 # output dimension
    pad_type: zero # padding type [zero/reflect]
    use_spade: True # whether to condition the decoding on other inferences, à la SPADE or not
    spade_kernel_size: 3 # kernel size within SPADE norm layers
    spade_param_free_norm: "instance" # what param-free normalization to apply in SPADE normalization
    spade_use_spectral_norm: True #
  w: # specific params for the water-segmentation decoder
    output_dim: 1
  encoder: # specific params for the encoder
    dim: 64 # dimension of the first projection before downsamplings
    input_dim: 3 # input number of channels
    n_downsample: 2 # number of downsampling layers in encoder
    n_res: 4 # number of residual blocks in content encoder/decoder
    norm: "none"

# -------------------------
# ----- Discriminator -----
# -------------------------
dis:
  soft_shift: 0.2 # label smoothing: real in U(1-soft_shift, 1), fake in U(0, soft_shift)
  flip_prob: 0.05 # label flipping
  opt:
    optimizer: ExtraAdam # one in [Adam, ExtraAdam] default: Adam
    beta1: 0.5
    lr: 0.0005
    lr_policy: step # constant or step ; if step, specify step_size and gamma
    lr_step_size: 30 # for linear decay
    lr_gamma: 0.5
  default: # default setting for discriminators (there are 4 of them for rn rf sn sf)
    input_nc: 3
    ndf: 64
    n_layers: 3
    norm: instance
    init_type: kaiming
    init_gain: 0.2
    use_sigmoid: false
# -------------------------------
# -----  Domain Classifier  -----
# -------------------------------
classifier:
  opt:
    optimizer: ExtraAdam # one in [Adam, ExtraAdam] default: Adam
    beta1: 0.5
    lr: 0.0005
    lr_policy: step # constant or step ; if step, specify step_size and gamma
    lr_step_size: 30 # for linear decay
    lr_gamma: 0.5
  loss: cross_entropy #Loss can be l1, l2, cross_entropy.  default cross_entropy
  layers: [100, 100, 20, 20, 4] # number of units per hidden layer ; las number is output_dim
  dropout: 0.4 # probability of being set to 0
  init_type: kaiming
  init_gain: 0.2

# ------------------------
# ----- Train Params -----
# ------------------------
train:
  epochs: 1000
  representational_training: False
  representation_steps: 0 # for how many steps would the representation be trained before we train the translation
  freeze_representation: False # whether or not to backprop into the representation when doing the translation
  lambdas: # scaling factors in the total loss
    default: 1 # default values for all tasks
    G:
      t:
        auto: 1 # auto-encoding, reconstruction
        cycle: 1 # cycle consistency
        gan: 1 # gan loss
        sm: 1 # semantic matching
      a:
        auto: 1 # auto-encoding, reconstruction
        cycle: 1 # cycle consistency
        gan: 1 # gan loss
      classifier: 1
    C: 1
  log_level: 1 # 0: no log, 1: only aggregated losses, >1 detailed losses

# -----------------------------
# ----- Validation Params -----
# -----------------------------
val:
  max_log_images: 15
  every_n_steps: 1000
  store_images: false
  infer_rec: true
  infer_idt: true # order: real, translated, rec, idt
