b: 4
batch_size: 4
flood_mask_binarization: 0.5
fuse: false
half: true
i: /home/mila/s/schmidtv/ccai/github/omnigan/config/website
images_paths: /home/mila/s/schmidtv/ccai/github/omnigan/config/website
keep_ratio_128: false
max_im_width: -1
n_images: -1
no_cloudy: false
no_conf: false
no_time: false
output_path: 'null'
overwrite: false
r: ../masker
resume_path: ../masker
upload: true
xla_purge_samples: -1
